name: CMake

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: mkdir build
      run: mkdir -p build
    - name: cd build
      run: cd build
    - name: cmake ..
      run: cmake ..
    - name: make
      run: make
