name: CMake

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: mkdir build
      run: mkdir -p build
    - name: cmake configure
      run: cd build && cmake ..
    - name: cmake build
      run: cmake --build build
